2023-03-09 22:59:50,547 INFO    StreamThr :39132 [internal.py:wandb_internal():87] W&B internal server running at pid: 39132, started at: 2023-03-09 22:59:50.546754
2023-03-09 22:59:50,553 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: status
2023-03-09 22:59:50,608 INFO    WriterThread:39132 [datastore.py:open_for_write():85] open: /Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_225950-oafcq15f/run-oafcq15f.wandb
2023-03-09 22:59:50,608 DEBUG   SenderThread:39132 [sender.py:send():336] send: header
2023-03-09 22:59:50,745 DEBUG   SenderThread:39132 [sender.py:send():336] send: run
2023-03-09 22:59:51,499 INFO    SenderThread:39132 [dir_watcher.py:__init__():219] watching files in: /Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_225950-oafcq15f/files
2023-03-09 22:59:51,499 INFO    SenderThread:39132 [sender.py:_start_run_threads():1078] run started: oafcq15f with start time 1678382990.546419
2023-03-09 22:59:51,613 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: summary_record
2023-03-09 22:59:51,613 INFO    SenderThread:39132 [sender.py:_save_file():1332] saving file wandb-summary.json with policy end
2023-03-09 22:59:51,745 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: check_version
2023-03-09 22:59:51,745 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: check_version
2023-03-09 22:59:51,809 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: run_start
2023-03-09 22:59:51,819 DEBUG   HandlerThread:39132 [system_info.py:__init__():31] System info init
2023-03-09 22:59:51,819 DEBUG   HandlerThread:39132 [system_info.py:__init__():46] System info init done
2023-03-09 22:59:51,819 INFO    HandlerThread:39132 [system_monitor.py:start():183] Starting system monitor
2023-03-09 22:59:51,819 INFO    SystemMonitor:39132 [system_monitor.py:_start():147] Starting system asset monitoring threads
2023-03-09 22:59:51,820 INFO    HandlerThread:39132 [system_monitor.py:probe():204] Collecting system info
2023-03-09 22:59:51,820 INFO    SystemMonitor:39132 [interfaces.py:start():187] Started cpu monitoring
2023-03-09 22:59:51,820 DEBUG   HandlerThread:39132 [system_info.py:probe():195] Probing system
2023-03-09 22:59:51,821 INFO    SystemMonitor:39132 [interfaces.py:start():187] Started disk monitoring
2023-03-09 22:59:51,821 INFO    SystemMonitor:39132 [interfaces.py:start():187] Started gpuapple monitoring
2023-03-09 22:59:51,822 INFO    SystemMonitor:39132 [interfaces.py:start():187] Started memory monitoring
2023-03-09 22:59:51,822 INFO    SystemMonitor:39132 [interfaces.py:start():187] Started network monitoring
2023-03-09 22:59:51,831 DEBUG   HandlerThread:39132 [system_info.py:_probe_git():180] Probing git
2023-03-09 22:59:51,863 DEBUG   HandlerThread:39132 [system_info.py:_probe_git():188] Probing git done
2023-03-09 22:59:51,863 DEBUG   HandlerThread:39132 [system_info.py:probe():240] Probing system done
2023-03-09 22:59:51,863 DEBUG   HandlerThread:39132 [system_monitor.py:probe():213] {'os': 'macOS-12.6-arm64-arm-64bit', 'python': '3.10.6', 'heartbeatAt': '2023-03-09T17:29:51.821443', 'startedAt': '2023-03-09T17:29:50.216768', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': 'Assignment_1-jvsc-173edaa7-afc5-4348-be7e-71ae9022e078791bf289-6135-4d8f-83ad-ca86107f3912.ipynb', 'root': '/Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1', 'git': {'remote': 'https://github.com/Bibhuti-Majhi/CS6910-Assignment-1.git', 'commit': '2f4ba94ae7966c377af4ae945bdaf0c224b93a3d'}, 'email': 'cs22m031@smail.iitm.ac.in', 'host': 'Bibhutis-Air.iitmlan', 'username': 'crysiswar999', 'executable': '/opt/homebrew/opt/python@3.10/bin/python3.10', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'total': 228.27386474609375, 'used': 99.73370361328125}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2023-03-09 22:59:51,863 INFO    HandlerThread:39132 [system_monitor.py:probe():214] Finished collecting system info
2023-03-09 22:59:51,863 INFO    HandlerThread:39132 [system_monitor.py:probe():217] Publishing system info
2023-03-09 22:59:51,863 DEBUG   HandlerThread:39132 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-03-09 22:59:51,864 DEBUG   HandlerThread:39132 [system_info.py:_save_pip():67] Saving pip packages done
2023-03-09 22:59:51,864 INFO    HandlerThread:39132 [system_monitor.py:probe():219] Finished publishing system info
2023-03-09 22:59:51,872 DEBUG   SenderThread:39132 [sender.py:send():336] send: files
2023-03-09 22:59:51,872 INFO    SenderThread:39132 [sender.py:_save_file():1332] saving file wandb-metadata.json with policy now
2023-03-09 22:59:51,883 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: stop_status
2023-03-09 22:59:51,884 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: stop_status
2023-03-09 22:59:52,234 DEBUG   SenderThread:39132 [sender.py:send():336] send: telemetry
2023-03-09 22:59:52,502 INFO    Thread-13 :39132 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_225950-oafcq15f/files/wandb-summary.json
2023-03-09 22:59:52,503 INFO    Thread-13 :39132 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_225950-oafcq15f/files/requirements.txt
2023-03-09 22:59:52,503 INFO    Thread-13 :39132 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_225950-oafcq15f/files/wandb-metadata.json
2023-03-09 22:59:52,801 INFO    wandb-upload_0:39132 [upload_job.py:push():138] Uploaded file /var/folders/lj/kz71w7bd4jq365nsc0cjx4mr0000gn/T/tmpjt7ummi7wandb/yoqwzumj-wandb-metadata.json
2023-03-09 22:59:56,255 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: status_report
2023-03-09 23:00:01,270 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: status_report
2023-03-09 23:00:06,300 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: status_report
2023-03-09 23:00:06,905 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: keepalive
2023-03-09 23:00:11,327 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: status_report
2023-03-09 23:00:11,929 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: keepalive
2023-03-09 23:00:16,348 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: status_report
2023-03-09 23:00:16,518 DEBUG   SenderThread:39132 [sender.py:send():336] send: exit
2023-03-09 23:00:16,518 INFO    SenderThread:39132 [sender.py:send_exit():559] handling exit code: 0
2023-03-09 23:00:16,520 INFO    SenderThread:39132 [sender.py:send_exit():561] handling runtime: 24
2023-03-09 23:00:16,522 INFO    SenderThread:39132 [sender.py:_save_file():1332] saving file wandb-summary.json with policy end
2023-03-09 23:00:16,522 INFO    SenderThread:39132 [sender.py:send_exit():567] send defer
2023-03-09 23:00:16,523 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: defer
2023-03-09 23:00:16,524 INFO    HandlerThread:39132 [handler.py:handle_request_defer():170] handle defer: 0
2023-03-09 23:00:16,525 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: defer
2023-03-09 23:00:16,525 INFO    SenderThread:39132 [sender.py:send_request_defer():583] handle sender defer: 0
2023-03-09 23:00:16,525 INFO    SenderThread:39132 [sender.py:transition_state():587] send defer: 1
2023-03-09 23:00:16,525 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: defer
2023-03-09 23:00:16,526 INFO    HandlerThread:39132 [handler.py:handle_request_defer():170] handle defer: 1
2023-03-09 23:00:16,526 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: defer
2023-03-09 23:00:16,526 INFO    SenderThread:39132 [sender.py:send_request_defer():583] handle sender defer: 1
2023-03-09 23:00:16,526 INFO    SenderThread:39132 [sender.py:transition_state():587] send defer: 2
2023-03-09 23:00:16,526 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: defer
2023-03-09 23:00:16,526 INFO    HandlerThread:39132 [handler.py:handle_request_defer():170] handle defer: 2
2023-03-09 23:00:16,526 INFO    HandlerThread:39132 [system_monitor.py:finish():193] Stopping system monitor
2023-03-09 23:00:16,543 DEBUG   SystemMonitor:39132 [system_monitor.py:_start():161] Starting system metrics aggregation loop
2023-03-09 23:00:16,544 INFO    HandlerThread:39132 [interfaces.py:finish():199] Joined cpu monitor
2023-03-09 23:00:16,544 DEBUG   SystemMonitor:39132 [system_monitor.py:_start():168] Finished system metrics aggregation loop
2023-03-09 23:00:16,544 INFO    HandlerThread:39132 [interfaces.py:finish():199] Joined disk monitor
2023-03-09 23:00:16,544 DEBUG   SystemMonitor:39132 [system_monitor.py:_start():172] Publishing last batch of metrics
2023-03-09 23:00:16,545 INFO    HandlerThread:39132 [interfaces.py:finish():199] Joined gpuapple monitor
2023-03-09 23:00:16,546 INFO    HandlerThread:39132 [interfaces.py:finish():199] Joined memory monitor
2023-03-09 23:00:16,546 INFO    HandlerThread:39132 [interfaces.py:finish():199] Joined network monitor
2023-03-09 23:00:16,547 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: defer
2023-03-09 23:00:16,547 INFO    SenderThread:39132 [sender.py:send_request_defer():583] handle sender defer: 2
2023-03-09 23:00:16,547 INFO    SenderThread:39132 [sender.py:transition_state():587] send defer: 3
2023-03-09 23:00:16,547 DEBUG   SenderThread:39132 [sender.py:send():336] send: telemetry
2023-03-09 23:00:16,547 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: defer
2023-03-09 23:00:16,548 DEBUG   SenderThread:39132 [sender.py:send():336] send: stats
2023-03-09 23:00:16,548 INFO    HandlerThread:39132 [handler.py:handle_request_defer():170] handle defer: 3
2023-03-09 23:00:16,548 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: defer
2023-03-09 23:00:16,548 INFO    SenderThread:39132 [sender.py:send_request_defer():583] handle sender defer: 3
2023-03-09 23:00:16,548 INFO    SenderThread:39132 [sender.py:transition_state():587] send defer: 4
2023-03-09 23:00:16,548 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: defer
2023-03-09 23:00:16,548 INFO    HandlerThread:39132 [handler.py:handle_request_defer():170] handle defer: 4
2023-03-09 23:00:16,549 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: defer
2023-03-09 23:00:16,549 INFO    SenderThread:39132 [sender.py:send_request_defer():583] handle sender defer: 4
2023-03-09 23:00:16,549 INFO    SenderThread:39132 [sender.py:transition_state():587] send defer: 5
2023-03-09 23:00:16,549 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: defer
2023-03-09 23:00:16,549 INFO    HandlerThread:39132 [handler.py:handle_request_defer():170] handle defer: 5
2023-03-09 23:00:16,549 DEBUG   SenderThread:39132 [sender.py:send():336] send: summary
2023-03-09 23:00:16,550 INFO    SenderThread:39132 [sender.py:_save_file():1332] saving file wandb-summary.json with policy end
2023-03-09 23:00:16,550 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: defer
2023-03-09 23:00:16,550 INFO    SenderThread:39132 [sender.py:send_request_defer():583] handle sender defer: 5
2023-03-09 23:00:16,550 INFO    SenderThread:39132 [sender.py:transition_state():587] send defer: 6
2023-03-09 23:00:16,550 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: defer
2023-03-09 23:00:16,550 INFO    HandlerThread:39132 [handler.py:handle_request_defer():170] handle defer: 6
2023-03-09 23:00:16,551 DEBUG   SenderThread:39132 [sender.py:send_request():363] send_request: defer
2023-03-09 23:00:16,551 INFO    SenderThread:39132 [sender.py:send_request_defer():583] handle sender defer: 6
2023-03-09 23:00:16,554 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: status_report
2023-03-09 23:00:16,640 INFO    Thread-13 :39132 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_225950-oafcq15f/files/wandb-summary.json
2023-03-09 23:00:17,095 ERROR   SenderThread:39132 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-09 23:00:17,095 ERROR   SenderThread:39132 [internal_api.py:execute():246] {"errors":[{"message":"run cs22m031/CS6910_DL_assignment_1/oafcq15f was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-09 23:00:17,523 DEBUG   HandlerThread:39132 [handler.py:handle_request():144] handle_request: poll_exit
2023-03-09 23:00:18,495 ERROR   SenderThread:39132 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-09 23:00:18,495 ERROR   SenderThread:39132 [internal_api.py:execute():246] {"errors":[{"message":"run cs22m031/CS6910_DL_assignment_1/oafcq15f was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-09 23:00:19,080 ERROR   FileStreamThread:39132 [file_stream.py:_thread_except_body():496] generic exception in filestream thread
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 492, in _thread_except_body
    self._thread_body()
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 448, in _thread_body
    success = self._send(ready_chunks, uploaded=uploaded)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 537, in _send
    self._handle_response(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 503, in _handle_response
    wandb.termerror(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/opt/homebrew/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
BrokenPipeError: [Errno 32] Broken pipe
2023-03-09 23:00:21,121 ERROR   SenderThread:39132 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-09 23:00:21,121 ERROR   SenderThread:39132 [internal_api.py:execute():246] {"errors":[{"message":"run cs22m031/CS6910_DL_assignment_1/oafcq15f was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-09 23:00:21,537 INFO    HandlerThread:39132 [handler.py:finish():842] shutting down handler
2023-03-09 23:00:21,538 INFO    WriterThread:39132 [datastore.py:close():298] close: /Users/crysiswar999/Documents/GitHub/CS6910-Assignment-1/wandb/run-20230309_225950-oafcq15f/run-oafcq15f.wandb
2023-03-09 23:00:21,691 ERROR   StreamThr :39132 [internal.py:wandb_internal():175] Thread SenderThread:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 242, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/opt/homebrew/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1588, in upsert_run
    response = self.gql(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 214, in gql
    ret = self._retry_gql(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 247, in execute
    self.display_gorilla_error_if_found(res)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 263, in display_gorilla_error_if_found
    wandb.termerror(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/opt/homebrew/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 329, in _process
    self._sm.send(record)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 343, in send
    send_handler(record)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 365, in send_request
    send_handler(record)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 609, in send_request_defer
    self.debounce(final=True)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 512, in debounce
    self._maybe_update_config(always=final)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 489, in _maybe_update_config
    self._debounce_config()
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 518, in _debounce_config
    self._api.upsert_run(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/apis/normalize.py", line 65, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1588, in upsert_run
    response = self.gql(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 214, in gql
    ret = self._retry_gql(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 247, in execute
    self.display_gorilla_error_if_found(res)
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 263, in display_gorilla_error_if_found
    wandb.termerror(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/opt/homebrew/lib/python3.10/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/opt/homebrew/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
wandb.errors.CommError: [Errno 32] Broken pipe
